#!/bin/bash

FEED="$1"
OUTPUT_DIR="$2"
BUILD_PARALLEL="$3"

# check for dependencies
DEPS="docker-hub docker"

for package in $DEPS; do
	which $package > /dev/null
	if [ $? != 0 ]; then
		echo "Dependencies: $DEPS"
		echo "Package $package is not installed."
		echo "Exiting..."
		exit 1
	fi
done

# download freifunk_release file from repo and determine sdk-version for feed
BRANCH=$(echo "$FEED" | cut -d'^' -f 2)
FREIFUNK_RELEASE="https://raw.githubusercontent.com/freifunk-berlin/falter-packages/${BRANCH}/packages/falter-common/files-common/etc/freifunk_release"
TMP=$(curl -s $FREIFUNK_RELEASE)
eval $TMP

sdks=(
	"apm821xx-nand"
	"at91-sama5"
	"ath79-generic"
	"bcm27xx-bcm2708"
	"bcm47xx-legacy"
	"bcm47xx-mips74k"
	"bcm53xx-generic"
	"bcm63xx-generic"
	"gemini-generic"
	"ipq40xx-generic"
	"ipq806x-generic"
	"kirkwood-generic"
	"layerscape-armv8_64b"
	"mpc85xx-p1010"
	"mvebu-cortexa72"
	"mvebu-cortexa9"
	"mxs-generic"
	"octeon-generic"
	"oxnas-ox820"
	"pistachio-generic"
	"ramips-mt7620"
	"ramips-rt288x"
	"sunxi-cortexa7"
	"sunxi-cortexa8"
	"x86-64"
	"x86-generic"
	"x86-geode"
	"zynq-generic"
	"mediatek-mt7622"
)

for SDK in ${sdks[@]}; do
	[ "$FREIFUNK_OPENWRT_BASE" != "snapshot" ] && SDK+="-$FREIFUNK_OPENWRT_BASE"
	echo "building $SDK"
	if [ -n "$BUILD_PARALLEL" ]; then
		(./build_feed "$SDK" "$FEED" "$OUTPUT_DIR" PARALLEL) &
	else
		./build_feed "$SDK" "$FEED" "$OUTPUT_DIR"
	fi
done
